<?xml version="1.0" encoding="utf-8"?><Database Name="Project Monitoring" Class="CRUDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=MAISYA\SQLEXPRESS;Initial Catalog=&quot;Project Monitoring&quot;;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Project_MonitoringConnectionString" Provider="System.Data.SqlClient" />
</Database>