#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexigoApi.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Project Monitoring")]
	public partial class ProjectMonitorDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDeveloper(Developer instance);
    partial void UpdateDeveloper(Developer instance);
    partial void DeleteDeveloper(Developer instance);
    partial void InsertProjectManager(ProjectManager instance);
    partial void UpdateProjectManager(ProjectManager instance);
    partial void DeleteProjectManager(ProjectManager instance);
    partial void InsertScrumMaster(ScrumMaster instance);
    partial void UpdateScrumMaster(ScrumMaster instance);
    partial void DeleteScrumMaster(ScrumMaster instance);
    #endregion
		
		public ProjectMonitorDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Project_MonitoringConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectMonitorDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectMonitorDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectMonitorDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProjectMonitorDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
		
		public System.Data.Linq.Table<Developer> Developers
		{
			get
			{
				return this.GetTable<Developer>();
			}
		}
		
		public System.Data.Linq.Table<ProjectManager> ProjectManagers
		{
			get
			{
				return this.GetTable<ProjectManager>();
			}
		}
		
		public System.Data.Linq.Table<ScrumMaster> ScrumMasters
		{
			get
			{
				return this.GetTable<ScrumMaster>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee
	{
		
		private int _ID;
		
		private string _Name;
		
		private System.Nullable<int> _SPV_ID;
		
		private string _Email;
		
		private string _Location_Code;
		
		private System.Nullable<System.DateTime> _Joined_date;
		
		private string _Sex;
		
		private string _DIV_Code;
		
		private string _Unit_Code;
		
		private string _Staff_Level;
		
		private string _Job_Family;
		
		private string _Job_Title;
		
		private System.Nullable<bool> _Expat;
		
		private System.Nullable<bool> _Contract;
		
		private string _Password;
		
		private System.Nullable<int> _Balance;
		
		public Employee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPV_ID", DbType="Int")]
		public System.Nullable<int> SPV_ID
		{
			get
			{
				return this._SPV_ID;
			}
			set
			{
				if ((this._SPV_ID != value))
				{
					this._SPV_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location_Code", DbType="NVarChar(50)")]
		public string Location_Code
		{
			get
			{
				return this._Location_Code;
			}
			set
			{
				if ((this._Location_Code != value))
				{
					this._Location_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Joined_date", DbType="Date")]
		public System.Nullable<System.DateTime> Joined_date
		{
			get
			{
				return this._Joined_date;
			}
			set
			{
				if ((this._Joined_date != value))
				{
					this._Joined_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(50)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this._Sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIV_Code", DbType="NVarChar(50)")]
		public string DIV_Code
		{
			get
			{
				return this._DIV_Code;
			}
			set
			{
				if ((this._DIV_Code != value))
				{
					this._DIV_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit_Code", DbType="NVarChar(50)")]
		public string Unit_Code
		{
			get
			{
				return this._Unit_Code;
			}
			set
			{
				if ((this._Unit_Code != value))
				{
					this._Unit_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_Level", DbType="NVarChar(50)")]
		public string Staff_Level
		{
			get
			{
				return this._Staff_Level;
			}
			set
			{
				if ((this._Staff_Level != value))
				{
					this._Staff_Level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_Family", DbType="NVarChar(50)")]
		public string Job_Family
		{
			get
			{
				return this._Job_Family;
			}
			set
			{
				if ((this._Job_Family != value))
				{
					this._Job_Family = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Job_Title", DbType="NVarChar(50)")]
		public string Job_Title
		{
			get
			{
				return this._Job_Title;
			}
			set
			{
				if ((this._Job_Title != value))
				{
					this._Job_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expat", DbType="Bit")]
		public System.Nullable<bool> Expat
		{
			get
			{
				return this._Expat;
			}
			set
			{
				if ((this._Expat != value))
				{
					this._Expat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract", DbType="Bit")]
		public System.Nullable<bool> Contract
		{
			get
			{
				return this._Contract;
			}
			set
			{
				if ((this._Contract != value))
				{
					this._Contract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int")]
		public System.Nullable<int> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Developer")]
	public partial class Developer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ITCM_SR_HPPID;
		
		private string _Issue;
		
		private string _Raise_Date;
		
		private string _Attachment;
		
		private string _Solution;
		
		private string _Status;
		
		private string _history;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnITCM_SR_HPPIDChanging(int value);
    partial void OnITCM_SR_HPPIDChanged();
    partial void OnIssueChanging(string value);
    partial void OnIssueChanged();
    partial void OnRaise_DateChanging(string value);
    partial void OnRaise_DateChanged();
    partial void OnAttachmentChanging(string value);
    partial void OnAttachmentChanged();
    partial void OnSolutionChanging(string value);
    partial void OnSolutionChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnhistoryChanging(string value);
    partial void OnhistoryChanged();
    #endregion
		
		public Developer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITCM_SR_HPPID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ITCM_SR_HPPID
		{
			get
			{
				return this._ITCM_SR_HPPID;
			}
			set
			{
				if ((this._ITCM_SR_HPPID != value))
				{
					this.OnITCM_SR_HPPIDChanging(value);
					this.SendPropertyChanging();
					this._ITCM_SR_HPPID = value;
					this.SendPropertyChanged("ITCM_SR_HPPID");
					this.OnITCM_SR_HPPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Issue", DbType="NVarChar(500)")]
		public string Issue
		{
			get
			{
				return this._Issue;
			}
			set
			{
				if ((this._Issue != value))
				{
					this.OnIssueChanging(value);
					this.SendPropertyChanging();
					this._Issue = value;
					this.SendPropertyChanged("Issue");
					this.OnIssueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Raise_Date", DbType="NVarChar(20)")]
		public string Raise_Date
		{
			get
			{
				return this._Raise_Date;
			}
			set
			{
				if ((this._Raise_Date != value))
				{
					this.OnRaise_DateChanging(value);
					this.SendPropertyChanging();
					this._Raise_Date = value;
					this.SendPropertyChanged("Raise_Date");
					this.OnRaise_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attachment", DbType="NVarChar(100)")]
		public string Attachment
		{
			get
			{
				return this._Attachment;
			}
			set
			{
				if ((this._Attachment != value))
				{
					this.OnAttachmentChanging(value);
					this.SendPropertyChanging();
					this._Attachment = value;
					this.SendPropertyChanged("Attachment");
					this.OnAttachmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solution", DbType="NVarChar(300)")]
		public string Solution
		{
			get
			{
				return this._Solution;
			}
			set
			{
				if ((this._Solution != value))
				{
					this.OnSolutionChanging(value);
					this.SendPropertyChanging();
					this._Solution = value;
					this.SendPropertyChanged("Solution");
					this.OnSolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history", DbType="NVarChar(200)")]
		public string history
		{
			get
			{
				return this._history;
			}
			set
			{
				if ((this._history != value))
				{
					this.OnhistoryChanging(value);
					this.SendPropertyChanging();
					this._history = value;
					this.SendPropertyChanged("history");
					this.OnhistoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProjectManager")]
	public partial class ProjectManager : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ITCM_SR_HPPID;
		
		private string _ProjectTitle;
		
		private string _Business_Analyst;
		
		private string _Web_Project_Identity;
		
		private string _Project_Controller;
		
		private string _Department;
		
		private string _Project_Type;
		
		private string _Key_User;
		
		private string _Star_Date;
		
		private string _Priority_Type;
		
		private string _Usage;
		
		private string _Note;
		
		private string _Total_Manhours;
		
		private string _Ended;
		
		private string _Ready_for_BA_Testing;
		
		private string _UAT;
		
		private string _LIVE;
		
		private string _Total_Manhours1;
		
		private string _Ended1;
		
		private string _Ready_for_BA_Testing1;
		
		private string _UAT1;
		
		private string _LIVE1;
		
		private string _history;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnITCM_SR_HPPIDChanging(string value);
    partial void OnITCM_SR_HPPIDChanged();
    partial void OnProjectTitleChanging(string value);
    partial void OnProjectTitleChanged();
    partial void OnBusiness_AnalystChanging(string value);
    partial void OnBusiness_AnalystChanged();
    partial void OnWeb_Project_IdentityChanging(string value);
    partial void OnWeb_Project_IdentityChanged();
    partial void OnProject_ControllerChanging(string value);
    partial void OnProject_ControllerChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnProject_TypeChanging(string value);
    partial void OnProject_TypeChanged();
    partial void OnKey_UserChanging(string value);
    partial void OnKey_UserChanged();
    partial void OnStar_DateChanging(string value);
    partial void OnStar_DateChanged();
    partial void OnPriority_TypeChanging(string value);
    partial void OnPriority_TypeChanged();
    partial void OnUsageChanging(string value);
    partial void OnUsageChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnTotal_ManhoursChanging(string value);
    partial void OnTotal_ManhoursChanged();
    partial void OnEndedChanging(string value);
    partial void OnEndedChanged();
    partial void OnReady_for_BA_TestingChanging(string value);
    partial void OnReady_for_BA_TestingChanged();
    partial void OnUATChanging(string value);
    partial void OnUATChanged();
    partial void OnLIVEChanging(string value);
    partial void OnLIVEChanged();
    partial void OnTotal_Manhours1Changing(string value);
    partial void OnTotal_Manhours1Changed();
    partial void OnEnded1Changing(string value);
    partial void OnEnded1Changed();
    partial void OnReady_for_BA_Testing1Changing(string value);
    partial void OnReady_for_BA_Testing1Changed();
    partial void OnUAT1Changing(string value);
    partial void OnUAT1Changed();
    partial void OnLIVE1Changing(string value);
    partial void OnLIVE1Changed();
    partial void OnhistoryChanging(string value);
    partial void OnhistoryChanged();
    #endregion
		
		public ProjectManager()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITCM_SR_HPPID", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ITCM_SR_HPPID
		{
			get
			{
				return this._ITCM_SR_HPPID;
			}
			set
			{
				if ((this._ITCM_SR_HPPID != value))
				{
					this.OnITCM_SR_HPPIDChanging(value);
					this.SendPropertyChanging();
					this._ITCM_SR_HPPID = value;
					this.SendPropertyChanged("ITCM_SR_HPPID");
					this.OnITCM_SR_HPPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProjectTitle", DbType="NVarChar(100)")]
		public string ProjectTitle
		{
			get
			{
				return this._ProjectTitle;
			}
			set
			{
				if ((this._ProjectTitle != value))
				{
					this.OnProjectTitleChanging(value);
					this.SendPropertyChanging();
					this._ProjectTitle = value;
					this.SendPropertyChanged("ProjectTitle");
					this.OnProjectTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Business_Analyst", DbType="NVarChar(100)")]
		public string Business_Analyst
		{
			get
			{
				return this._Business_Analyst;
			}
			set
			{
				if ((this._Business_Analyst != value))
				{
					this.OnBusiness_AnalystChanging(value);
					this.SendPropertyChanging();
					this._Business_Analyst = value;
					this.SendPropertyChanged("Business_Analyst");
					this.OnBusiness_AnalystChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Web_Project_Identity", DbType="NVarChar(100)")]
		public string Web_Project_Identity
		{
			get
			{
				return this._Web_Project_Identity;
			}
			set
			{
				if ((this._Web_Project_Identity != value))
				{
					this.OnWeb_Project_IdentityChanging(value);
					this.SendPropertyChanging();
					this._Web_Project_Identity = value;
					this.SendPropertyChanged("Web_Project_Identity");
					this.OnWeb_Project_IdentityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Project_Controller", DbType="NVarChar(100)")]
		public string Project_Controller
		{
			get
			{
				return this._Project_Controller;
			}
			set
			{
				if ((this._Project_Controller != value))
				{
					this.OnProject_ControllerChanging(value);
					this.SendPropertyChanging();
					this._Project_Controller = value;
					this.SendPropertyChanged("Project_Controller");
					this.OnProject_ControllerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NVarChar(100)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Project_Type", DbType="NVarChar(100)")]
		public string Project_Type
		{
			get
			{
				return this._Project_Type;
			}
			set
			{
				if ((this._Project_Type != value))
				{
					this.OnProject_TypeChanging(value);
					this.SendPropertyChanging();
					this._Project_Type = value;
					this.SendPropertyChanged("Project_Type");
					this.OnProject_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Key_User", DbType="NVarChar(100)")]
		public string Key_User
		{
			get
			{
				return this._Key_User;
			}
			set
			{
				if ((this._Key_User != value))
				{
					this.OnKey_UserChanging(value);
					this.SendPropertyChanging();
					this._Key_User = value;
					this.SendPropertyChanged("Key_User");
					this.OnKey_UserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Star_Date", DbType="NVarChar(50)")]
		public string Star_Date
		{
			get
			{
				return this._Star_Date;
			}
			set
			{
				if ((this._Star_Date != value))
				{
					this.OnStar_DateChanging(value);
					this.SendPropertyChanging();
					this._Star_Date = value;
					this.SendPropertyChanged("Star_Date");
					this.OnStar_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority_Type", DbType="NVarChar(100)")]
		public string Priority_Type
		{
			get
			{
				return this._Priority_Type;
			}
			set
			{
				if ((this._Priority_Type != value))
				{
					this.OnPriority_TypeChanging(value);
					this.SendPropertyChanging();
					this._Priority_Type = value;
					this.SendPropertyChanged("Priority_Type");
					this.OnPriority_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usage", DbType="NVarChar(500)")]
		public string Usage
		{
			get
			{
				return this._Usage;
			}
			set
			{
				if ((this._Usage != value))
				{
					this.OnUsageChanging(value);
					this.SendPropertyChanging();
					this._Usage = value;
					this.SendPropertyChanged("Usage");
					this.OnUsageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(500)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Manhours", DbType="NVarChar(10)")]
		public string Total_Manhours
		{
			get
			{
				return this._Total_Manhours;
			}
			set
			{
				if ((this._Total_Manhours != value))
				{
					this.OnTotal_ManhoursChanging(value);
					this.SendPropertyChanging();
					this._Total_Manhours = value;
					this.SendPropertyChanged("Total_Manhours");
					this.OnTotal_ManhoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ended", DbType="NVarChar(30)")]
		public string Ended
		{
			get
			{
				return this._Ended;
			}
			set
			{
				if ((this._Ended != value))
				{
					this.OnEndedChanging(value);
					this.SendPropertyChanging();
					this._Ended = value;
					this.SendPropertyChanged("Ended");
					this.OnEndedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready_for_BA_Testing", DbType="NVarChar(30)")]
		public string Ready_for_BA_Testing
		{
			get
			{
				return this._Ready_for_BA_Testing;
			}
			set
			{
				if ((this._Ready_for_BA_Testing != value))
				{
					this.OnReady_for_BA_TestingChanging(value);
					this.SendPropertyChanging();
					this._Ready_for_BA_Testing = value;
					this.SendPropertyChanged("Ready_for_BA_Testing");
					this.OnReady_for_BA_TestingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAT", DbType="NVarChar(50)")]
		public string UAT
		{
			get
			{
				return this._UAT;
			}
			set
			{
				if ((this._UAT != value))
				{
					this.OnUATChanging(value);
					this.SendPropertyChanging();
					this._UAT = value;
					this.SendPropertyChanged("UAT");
					this.OnUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIVE", DbType="NVarChar(50)")]
		public string LIVE
		{
			get
			{
				return this._LIVE;
			}
			set
			{
				if ((this._LIVE != value))
				{
					this.OnLIVEChanging(value);
					this.SendPropertyChanging();
					this._LIVE = value;
					this.SendPropertyChanged("LIVE");
					this.OnLIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Manhours1", DbType="NVarChar(10)")]
		public string Total_Manhours1
		{
			get
			{
				return this._Total_Manhours1;
			}
			set
			{
				if ((this._Total_Manhours1 != value))
				{
					this.OnTotal_Manhours1Changing(value);
					this.SendPropertyChanging();
					this._Total_Manhours1 = value;
					this.SendPropertyChanged("Total_Manhours1");
					this.OnTotal_Manhours1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ended1", DbType="NVarChar(50)")]
		public string Ended1
		{
			get
			{
				return this._Ended1;
			}
			set
			{
				if ((this._Ended1 != value))
				{
					this.OnEnded1Changing(value);
					this.SendPropertyChanging();
					this._Ended1 = value;
					this.SendPropertyChanged("Ended1");
					this.OnEnded1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready_for_BA_Testing1", DbType="NVarChar(50)")]
		public string Ready_for_BA_Testing1
		{
			get
			{
				return this._Ready_for_BA_Testing1;
			}
			set
			{
				if ((this._Ready_for_BA_Testing1 != value))
				{
					this.OnReady_for_BA_Testing1Changing(value);
					this.SendPropertyChanging();
					this._Ready_for_BA_Testing1 = value;
					this.SendPropertyChanged("Ready_for_BA_Testing1");
					this.OnReady_for_BA_Testing1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAT1", DbType="NVarChar(50)")]
		public string UAT1
		{
			get
			{
				return this._UAT1;
			}
			set
			{
				if ((this._UAT1 != value))
				{
					this.OnUAT1Changing(value);
					this.SendPropertyChanging();
					this._UAT1 = value;
					this.SendPropertyChanged("UAT1");
					this.OnUAT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIVE1", DbType="NVarChar(50)")]
		public string LIVE1
		{
			get
			{
				return this._LIVE1;
			}
			set
			{
				if ((this._LIVE1 != value))
				{
					this.OnLIVE1Changing(value);
					this.SendPropertyChanging();
					this._LIVE1 = value;
					this.SendPropertyChanged("LIVE1");
					this.OnLIVE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history", DbType="NVarChar(500)")]
		public string history
		{
			get
			{
				return this._history;
			}
			set
			{
				if ((this._history != value))
				{
					this.OnhistoryChanging(value);
					this.SendPropertyChanging();
					this._history = value;
					this.SendPropertyChanged("history");
					this.OnhistoryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ScrumMaster")]
	public partial class ScrumMaster : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ITCM_SR_HPPID;
		
		private string _Total_Manhours;
		
		private string _Ended;
		
		private string _Ready_for_BA_Testing;
		
		private string _UAT;
		
		private string _LIVE;
		
		private string _Total_Manhours1;
		
		private string _Ended1;
		
		private string _Ready_for_BA_Testing1;
		
		private string _UAT1;
		
		private string _LIVE1;
		
		private string _Status;
		
		private System.Nullable<int> _Completion;
		
		private string _Last_Update;
		
		private string _Progress_History;
		
		private string _Teams;
		
		private string _Conf_Type;
		
		private string _Conf_Value;
		
		private string _history;
		
		private string _Attachment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnITCM_SR_HPPIDChanging(string value);
    partial void OnITCM_SR_HPPIDChanged();
    partial void OnTotal_ManhoursChanging(string value);
    partial void OnTotal_ManhoursChanged();
    partial void OnEndedChanging(string value);
    partial void OnEndedChanged();
    partial void OnReady_for_BA_TestingChanging(string value);
    partial void OnReady_for_BA_TestingChanged();
    partial void OnUATChanging(string value);
    partial void OnUATChanged();
    partial void OnLIVEChanging(string value);
    partial void OnLIVEChanged();
    partial void OnTotal_Manhours1Changing(string value);
    partial void OnTotal_Manhours1Changed();
    partial void OnEnded1Changing(string value);
    partial void OnEnded1Changed();
    partial void OnReady_for_BA_Testing1Changing(string value);
    partial void OnReady_for_BA_Testing1Changed();
    partial void OnUAT1Changing(string value);
    partial void OnUAT1Changed();
    partial void OnLIVE1Changing(string value);
    partial void OnLIVE1Changed();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnCompletionChanging(System.Nullable<int> value);
    partial void OnCompletionChanged();
    partial void OnLast_UpdateChanging(string value);
    partial void OnLast_UpdateChanged();
    partial void OnProgress_HistoryChanging(string value);
    partial void OnProgress_HistoryChanged();
    partial void OnTeamsChanging(string value);
    partial void OnTeamsChanged();
    partial void OnConf_TypeChanging(string value);
    partial void OnConf_TypeChanged();
    partial void OnConf_ValueChanging(string value);
    partial void OnConf_ValueChanged();
    partial void OnhistoryChanging(string value);
    partial void OnhistoryChanged();
    partial void OnAttachmentChanging(string value);
    partial void OnAttachmentChanged();
    #endregion
		
		public ScrumMaster()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ITCM_SR_HPPID", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ITCM_SR_HPPID
		{
			get
			{
				return this._ITCM_SR_HPPID;
			}
			set
			{
				if ((this._ITCM_SR_HPPID != value))
				{
					this.OnITCM_SR_HPPIDChanging(value);
					this.SendPropertyChanging();
					this._ITCM_SR_HPPID = value;
					this.SendPropertyChanged("ITCM_SR_HPPID");
					this.OnITCM_SR_HPPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Manhours", DbType="NVarChar(10)")]
		public string Total_Manhours
		{
			get
			{
				return this._Total_Manhours;
			}
			set
			{
				if ((this._Total_Manhours != value))
				{
					this.OnTotal_ManhoursChanging(value);
					this.SendPropertyChanging();
					this._Total_Manhours = value;
					this.SendPropertyChanged("Total_Manhours");
					this.OnTotal_ManhoursChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ended", DbType="NVarChar(30)")]
		public string Ended
		{
			get
			{
				return this._Ended;
			}
			set
			{
				if ((this._Ended != value))
				{
					this.OnEndedChanging(value);
					this.SendPropertyChanging();
					this._Ended = value;
					this.SendPropertyChanged("Ended");
					this.OnEndedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready_for_BA_Testing", DbType="NVarChar(30)")]
		public string Ready_for_BA_Testing
		{
			get
			{
				return this._Ready_for_BA_Testing;
			}
			set
			{
				if ((this._Ready_for_BA_Testing != value))
				{
					this.OnReady_for_BA_TestingChanging(value);
					this.SendPropertyChanging();
					this._Ready_for_BA_Testing = value;
					this.SendPropertyChanged("Ready_for_BA_Testing");
					this.OnReady_for_BA_TestingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAT", DbType="NVarChar(50)")]
		public string UAT
		{
			get
			{
				return this._UAT;
			}
			set
			{
				if ((this._UAT != value))
				{
					this.OnUATChanging(value);
					this.SendPropertyChanging();
					this._UAT = value;
					this.SendPropertyChanged("UAT");
					this.OnUATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIVE", DbType="NVarChar(50)")]
		public string LIVE
		{
			get
			{
				return this._LIVE;
			}
			set
			{
				if ((this._LIVE != value))
				{
					this.OnLIVEChanging(value);
					this.SendPropertyChanging();
					this._LIVE = value;
					this.SendPropertyChanged("LIVE");
					this.OnLIVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Manhours1", DbType="NVarChar(10)")]
		public string Total_Manhours1
		{
			get
			{
				return this._Total_Manhours1;
			}
			set
			{
				if ((this._Total_Manhours1 != value))
				{
					this.OnTotal_Manhours1Changing(value);
					this.SendPropertyChanging();
					this._Total_Manhours1 = value;
					this.SendPropertyChanged("Total_Manhours1");
					this.OnTotal_Manhours1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ended1", DbType="NVarChar(50)")]
		public string Ended1
		{
			get
			{
				return this._Ended1;
			}
			set
			{
				if ((this._Ended1 != value))
				{
					this.OnEnded1Changing(value);
					this.SendPropertyChanging();
					this._Ended1 = value;
					this.SendPropertyChanged("Ended1");
					this.OnEnded1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ready_for_BA_Testing1", DbType="NVarChar(50)")]
		public string Ready_for_BA_Testing1
		{
			get
			{
				return this._Ready_for_BA_Testing1;
			}
			set
			{
				if ((this._Ready_for_BA_Testing1 != value))
				{
					this.OnReady_for_BA_Testing1Changing(value);
					this.SendPropertyChanging();
					this._Ready_for_BA_Testing1 = value;
					this.SendPropertyChanged("Ready_for_BA_Testing1");
					this.OnReady_for_BA_Testing1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UAT1", DbType="NVarChar(50)")]
		public string UAT1
		{
			get
			{
				return this._UAT1;
			}
			set
			{
				if ((this._UAT1 != value))
				{
					this.OnUAT1Changing(value);
					this.SendPropertyChanging();
					this._UAT1 = value;
					this.SendPropertyChanged("UAT1");
					this.OnUAT1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LIVE1", DbType="NVarChar(50)")]
		public string LIVE1
		{
			get
			{
				return this._LIVE1;
			}
			set
			{
				if ((this._LIVE1 != value))
				{
					this.OnLIVE1Changing(value);
					this.SendPropertyChanging();
					this._LIVE1 = value;
					this.SendPropertyChanged("LIVE1");
					this.OnLIVE1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(100)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Completion", DbType="Int")]
		public System.Nullable<int> Completion
		{
			get
			{
				return this._Completion;
			}
			set
			{
				if ((this._Completion != value))
				{
					this.OnCompletionChanging(value);
					this.SendPropertyChanging();
					this._Completion = value;
					this.SendPropertyChanged("Completion");
					this.OnCompletionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_Update", DbType="NVarChar(100)")]
		public string Last_Update
		{
			get
			{
				return this._Last_Update;
			}
			set
			{
				if ((this._Last_Update != value))
				{
					this.OnLast_UpdateChanging(value);
					this.SendPropertyChanging();
					this._Last_Update = value;
					this.SendPropertyChanged("Last_Update");
					this.OnLast_UpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Progress_History", DbType="NVarChar(100)")]
		public string Progress_History
		{
			get
			{
				return this._Progress_History;
			}
			set
			{
				if ((this._Progress_History != value))
				{
					this.OnProgress_HistoryChanging(value);
					this.SendPropertyChanging();
					this._Progress_History = value;
					this.SendPropertyChanged("Progress_History");
					this.OnProgress_HistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Teams", DbType="NVarChar(100)")]
		public string Teams
		{
			get
			{
				return this._Teams;
			}
			set
			{
				if ((this._Teams != value))
				{
					this.OnTeamsChanging(value);
					this.SendPropertyChanging();
					this._Teams = value;
					this.SendPropertyChanged("Teams");
					this.OnTeamsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conf_Type", DbType="NVarChar(50)")]
		public string Conf_Type
		{
			get
			{
				return this._Conf_Type;
			}
			set
			{
				if ((this._Conf_Type != value))
				{
					this.OnConf_TypeChanging(value);
					this.SendPropertyChanging();
					this._Conf_Type = value;
					this.SendPropertyChanged("Conf_Type");
					this.OnConf_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Conf_Value", DbType="NVarChar(50)")]
		public string Conf_Value
		{
			get
			{
				return this._Conf_Value;
			}
			set
			{
				if ((this._Conf_Value != value))
				{
					this.OnConf_ValueChanging(value);
					this.SendPropertyChanging();
					this._Conf_Value = value;
					this.SendPropertyChanged("Conf_Value");
					this.OnConf_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_history", DbType="NVarChar(500)")]
		public string history
		{
			get
			{
				return this._history;
			}
			set
			{
				if ((this._history != value))
				{
					this.OnhistoryChanging(value);
					this.SendPropertyChanging();
					this._history = value;
					this.SendPropertyChanged("history");
					this.OnhistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Attachment", DbType="NVarChar(50)")]
		public string Attachment
		{
			get
			{
				return this._Attachment;
			}
			set
			{
				if ((this._Attachment != value))
				{
					this.OnAttachmentChanging(value);
					this.SendPropertyChanging();
					this._Attachment = value;
					this.SendPropertyChanged("Attachment");
					this.OnAttachmentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
